# Generated by Django 5.2.8 on 2025-11-29 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=20, verbose_name='رمزعبور')),
                ('name', models.CharField(max_length=40, verbose_name='نام')),
                ('birthdate', models.DateField(verbose_name='تاریخ تولد')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره نلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('gender', models.CharField(choices=[('m', 'مرد'), ('f', 'زن'), ('n', 'نمی خواهم مشخص کنم')], max_length=10, verbose_name='جنسیت')),
            ],
            options={
                'verbose_name': 'کاربر ',
                'verbose_name_plural': 'کاربر',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوای پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='core.myuser', verbose_name='گیرنده پیام')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='core.myuser', verbose_name='فرستنده پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('status', models.CharField(choices=[('p', 'در انتظار'), ('a', 'درخواست دوستی را قبول کرد'), ('r', 'درخواست دوستی را قبول نکرد')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='core.myuser', verbose_name='درخواست دوستی از')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_request', to='core.myuser', verbose_name='درخواست دوستی به')),
            ],
            options={
                'verbose_name': 'درخواست دوستی',
                'verbose_name_plural': 'درخواست دوستی',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('published', models.BooleanField(default=False, verbose_name='منتشرشده')),
                ('published_at', models.DateTimeField(verbose_name='زمان انتشار')),
                ('rate', models.PositiveSmallIntegerField(verbose_name='امتیاز')),
                ('archived', models.BooleanField(default=False, verbose_name='آرشیو')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='بارگذاری عکس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.myuser', verbose_name='منتشرکننده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.myuser', verbose_name='پسندیده شده توسط')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='core.post', verbose_name='پست مربوطه')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوای کامنت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('Updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('Is_visible', models.BooleanField(default=True, verbose_name='قابل رویت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replied', to='core.comments', verbose_name='پاسخ به کامنت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.myuser', verbose_name='کامنت توسط')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='کامنت برای پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت',
            },
        ),
    ]
